config/routes.rb
DDB::Application.routes.draw do

  resources :password_resets

  resources :abouts

  resources :doctypes

  resources :documents

  resources :users

  resources :companies
  
  resources :sessions
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "companies#new", :as => "sign_up"
  get "log_in_phone" => "sessions#log_in_phone", :as => "log_in_phone"
  
  get "user_log_out" => "sessions#destroy_user", :as => "user_log_out"
  get "user_log_in" => "sessions#new_user", :as => "user_log_in"
  match '/sessions_create_user' => "sessions#create_user", :as => 'sessions_create_user'
  
  get "index_current_user_docs" => "documents#index_current_user_docs", :as => "index_current_user_docs"
  
  get "doc_phone" => "documents#doc_phone", :as => "doc_phone"
  post "email_doc" => "documents#email_doc", :as => "email_doc"

  match '/:company_usersname' => 'companies#show'
  
  root :to => "companies#home"
  
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user	
  belongs_to :company
  belongs_to :doctype
  
  attr_accessible :doc, :user_id, :description, :doctype_id
  
  has_attached_file :doc, :whiny => false, :styles => { :icon => ["48x63>", :jpg], :small => ["128x128>", :jpg], :medium => ["300x300>", :jpg], :large => ["1224x1584>", :jpg] }, #:styles      => {:icon => "50x50#", :thumb=> "100x100#", :small  => "190x190#", :large => "500x500>" },
  :url  => "/assets/docs/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/docs/:id/:style/:basename.:extension",
  :convert_options => { :large => '-quality 100' }

  #validates_attachment_size :doc, :less_than => 10.megabytes
  #validates_attachment_content_type :attached, :content_type => ['image/jpeg', 'image/png', 'application/pdf', 'application/octet-stream', 'application/msword']
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :require_company, :except => [:index_current_user_docs]	
  before_filter :require_user, :only => [:index_current_user_docs]
  skip_before_filter :require_company, :only => [:doc_phone, :email_doc]

	
  def email_doc
    @user = User.authenticate(params[:username], params[:password]);
    
    if @user #params[:user_id].to_i == @user.id 
      @doc = @user.documents.find(:first, :conditions => ['id = ?',params[:doc_id]], :order => 'updated_at desc')
      DdbMailer.doc_phone_email(@doc, params[:email_to]).deliver  
    end

    render :nothing => true
  end

  def doc_phone
    @user = User.authenticate(params[:username], params[:password]);
    
    if @user
      @docs = @user.documents.find(:all, :order => 'updated_at desc')

      docHashArray = []

      @docs.each do |a|

        eachHash = Hash.new
        eachHash['doc_id'] = a.id.to_s 
        eachHash['description'] = a.description 
        eachHash['doctype_name'] = a.doctype.name
        eachHash['doc_icon_url'] = request.protocol + request.host_with_port + a.doc.url(:icon)
        eachHash['doc_original_url'] = request.protocol + request.host_with_port + a.doc.url(:original)
        
        docHashArray << eachHash
      end

      respond_to do |format|
        format.iphone {
          render :json => docHashArray.to_json
        }   
        format.html {redirect_to root_url, :notice => "Logged in!"} 
        format.xml {redirect_to root_url, :notice => "Logged in!" }   
      end
    else
      flash[:notice] = "Invalid username or password"
      
      respond_to do |format|
        format.iphone {render :text => "No" }   
        format.html {render "new"} 
        format.xml {render "new"}   
      end
    end



  end

  # GET /documents
  # GET /documents.xml
  def index
    @documents = current_company.documents.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @documents }
    end
  end
  
  def index_current_user_docs
    @documents = current_user.documents.all

    respond_to do |format|
      format.html { render 'index.html.erb' }
      format.xml  { render :xml => @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.xml
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.xml
  def new
    @document = current_company.documents.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = current_company.documents.find(params[:id])
  end

  # POST /documents
  # POST /documents.xml
  def create
    @document = current_company.documents.new(params[:document])

    respond_to do |format|
      if @document.save
      	format.html { redirect_to(documents_path(), :notice => 'Document was successfully created.') }
        format.xml  { render :xml => @document, :status => :created, :location => @document }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.xml
  def update
    @document = current_company.documents.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to(documents_path(), :notice => 'Document was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.xml
  def destroy
    @document = current_company.documents.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to(documents_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document, :html => { :multipart => true }) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'User' %><br />
    <%= f.select :user_id, current_company.users.all.collect {|us| [ us.name, us.id ] } %>
  </div>
  <div class="field">
    <%= f.label 'Document Type' %><br />
    <%= f.select :doctype_id, current_company.doctypes.all.collect {|dt| [ dt.name, dt.id ] } %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label 'Document File' %><br />
    <%= f.file_field :doc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<div class="page_header">
  <h1>Documents</h1>
</div>

<div>
  <% if current_company %>
    <%= link_to 'New Document', new_document_path %>
  <% end %>	
</div>

<div class="all_docs_wrapper">
<% @documents.each do |document| %>
  <div class="document_wrapper">
  	<%= link_to image_tag(document.doc.url(:small)), document.doc.url(:original) %><br/></br/>
  	<%= document.user.name unless document.user.nil?  %><br />
    <%= document.doctype.name unless document.doctype.nil? %><br />	
    <%= document.description %>
    
    <% if current_company %>
      <br /><%= link_to 'Edit', edit_document_path(document) %>
      <br /><%= link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete %>
    <% end %>	
  </div>
<% end %>
</div>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @document.user_id %>
</p>

<p>
  <b>Doctype:</b>
  <%= @document.doctype_id %>
</p>

<p>
  <b>Description:</b>
  <%= @document.description %>
</p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>