config/routes.rb
DDB::Application.routes.draw do

  resources :password_resets

  resources :abouts

  resources :doctypes

  resources :documents

  resources :users

  resources :companies
  
  resources :sessions
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "companies#new", :as => "sign_up"
  get "log_in_phone" => "sessions#log_in_phone", :as => "log_in_phone"
  
  get "user_log_out" => "sessions#destroy_user", :as => "user_log_out"
  get "user_log_in" => "sessions#new_user", :as => "user_log_in"
  match '/sessions_create_user' => "sessions#create_user", :as => 'sessions_create_user'
  
  get "index_current_user_docs" => "documents#index_current_user_docs", :as => "index_current_user_docs"
  
  get "doc_phone" => "documents#doc_phone", :as => "doc_phone"
  post "email_doc" => "documents#email_doc", :as => "email_doc"

  match '/:company_usersname' => 'companies#show'
  
  root :to => "companies#home"
  
end

app/models/about.rb
class About < ActiveRecord::Base	
  belongs_to :company
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  # GET /abouts
  # GET /abouts.xml
  def index
    @abouts = About.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @abouts }
    end
  end

  # GET /abouts/1
  # GET /abouts/1.xml
  def show
    @about = About.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @about }
    end
  end

  # GET /abouts/new
  # GET /abouts/new.xml
  def new
    @about = About.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @about }
    end
  end

  # GET /abouts/1/edit
  def edit
    @about = About.find(params[:id])
  end

  # POST /abouts
  # POST /abouts.xml
  def create
    @about = About.new(params[:about])

    respond_to do |format|
      if @about.save
        format.html { redirect_to(@about, :notice => 'About was successfully created.') }
        format.xml  { render :xml => @about, :status => :created, :location => @about }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @about.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /abouts/1
  # PUT /abouts/1.xml
  def update
    @about = About.find(params[:id])

    respond_to do |format|
      if @about.update_attributes(params[:about])
        format.html { redirect_to(@about, :notice => 'About was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @about.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.xml
  def destroy
    @about = About.find(params[:id])
    @about.destroy

    respond_to do |format|
      format.html { redirect_to(abouts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<%= form_for(@about) do |f| %>
  <% if @about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% @about.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :about_url %><br />
    <%= f.text_field :about_url %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.text_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing about</h1>

<%= render 'form' %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<h1>Listing abouts</h1>

<table>
  <tr>
    <th>About url</th>
    <th>Company</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @abouts.each do |about| %>
  <tr>
    <td><%= about.about_url %></td>
    <td><%= about.company_id %></td>
    <td><%= about.title %></td>
    <td><%= about.description %></td>
    <td><%= link_to 'Show', about %></td>
    <td><%= link_to 'Edit', edit_about_path(about) %></td>
    <td><%= link_to 'Destroy', about, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New About', new_about_path %>

app/views/abouts/new.html.erb
<h1>New about</h1>

<%= render 'form' %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>About url:</b>
  <%= @about.about_url %>
</p>

<p>
  <b>Company:</b>
  <%= @about.company_id %>
</p>

<p>
  <b>Title:</b>
  <%= @about.title %>
</p>

<p>
  <b>Description:</b>
  <%= @about.description %>
</p>


<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>